def load_word_maps():
    return word_maps

word_maps = {
    # ========== MACHINE LEARNING & AI ==========
    # Related Domains: Computer Science, Mathematics, Data Science
    
    "ml": ["machine learning", "computer science", "data science"],
    "ai": ["artificial intelligence", "computer science", "machine learning"],
    "dl": ["deep learning", "machine learning", "computer science"],
    "ds": ["data science", "data structures", "machine learning", "computer science"],
    "dsa": ["data structures and algorithms", "computer science", "algorithms"],
    "algo": ["algorithms", "computer science", "mathematics"],
    "nlp": ["natural language processing", "artificial intelligence", "machine learning"],
    "cv": ["computer vision", "artificial intelligence", "machine learning"],
    "ai ml": ["artificial intelligence", "machine learning", "computer science"],
    "ds ml": ["data science", "machine learning", "computer science"],
    "ml dl": ["machine learning", "deep learning", "machine learning"],
    "neural": ["neural networks", "machine learning", "deep learning"],
    "deep net": ["deep networks", "deep learning", "machine learning"],
    "classification": ["classification", "machine learning", "data science"],
    "clustering": ["clustering", "machine learning", "data analysis"],
    "regression": ["regression", "machine learning", "statistics"],
    "supervised": ["supervised learning", "machine learning"],
    "unsupervised": ["unsupervised learning", "machine learning"],
    "reinforcement": ["reinforcement learning", "machine learning"],
    "transfer": ["transfer learning", "machine learning"],
    "nlp": ["natural language processing", "artificial intelligence", "text analysis"],
    "computer vision": ["computer vision", "artificial intelligence", "image processing"],
    "cv": ["computer vision", "artificial intelligence"],
    
    # ========== DATABASES & DATA MANAGEMENT ==========
    # Related Domains: Computer Science, Distributed Systems, Data Science
    
    "db": ["database", "databases", "computer science", "data management"],
    "dbms": ["database management system", "database management systems", "database", "computer science"],
    "sql": ["structured query language", "databases", "data querying"],
    "nosql": ["non relational databases", "mongodb", "cassandra", "databases"],
    "data eng": ["data engineering", "data pipelines", "databases"],
    "etl": ["extract transform load", "data pipelines", "data engineering"],
    "big data": ["big data", "data analytics", "hadoop", "spark", "data science"],
    "analytics": ["data analytics", "business intelligence", "data science"],
    "bi": ["business intelligence", "data analytics", "data science"],
    
    # ========== COMPUTER SCIENCE CORE ==========
    # Related Domains: Mathematics, Programming, Software Engineering
    "os": ["operating system", "operating systems", "computer science", "systems"],
    "cn": ["computer networks", "computer networking", "networking", "computer science"],
    "coa": ["computer organization and architecture", "computer science"],
    "ca": ["computer architecture", "computer organization", "computer science"],
    "toc": ["theory of computation", "computer science", "mathematics"],
    "cd": ["compiler design", "compilers", "programming languages"],
    "se": ["software engineering", "computer science", "programming"],
    "oop": ["object oriented programming", "object-oriented programming", "programming", "computer science"],
    "oops": ["object oriented programming", "object-oriented programming", "programming"],
    
    # Programming & Development
    # Related Domains: Computer Science, Software Engineering
    "prog": ["programming", "computer science"],
    "coding": ["programming", "software", "computer science"],
    "dev": ["development", "developer", "software engineering"],
    "web dev": ["web development", "computer science", "frontend"],
    "backend": ["backend systems", "server side", "web development"],
    "frontend": ["frontend", "client side", "web development"],
    "fullstack": ["full stack", "web development"],
    "api": ["application programming interface", "web services", "web development"],
    "ui": ["user interface", "design", "frontend", "web development"],
    "ux": ["user experience", "design", "frontend"],
    "py": ["python", "programming", "computer science"],
    "js": ["javascript", "programming", "web development"],
    "react": ["react", "web development", "frontend"],
    "typescript": ["typescript", "programming", "web development"],
    "nodejs": ["nodejs", "backend", "web development"],
    
    # ========== PETROLEUM ENGINEERING ==========
    # Related Domains: Engineering, Geology, Materials Science, Mining
    
    "petro": ["petroleum engineering", "oil and gas", "energy"],
    "reservoir": ["reservoir engineering", "petroleum engineering", "oil and gas"],
    "drilling": ["drilling engineering", "petroleum engineering", "oil and gas", "equipment"],
    "production": ["production engineering", "petroleum engineering", "oil and gas"],
    "subsea": ["subsea engineering", "offshore engineering", "petroleum engineering"],
    "offshore": ["offshore engineering", "marine engineering", "petroleum engineering"],
    "cbm": ["coal bed methane", "methane extraction", "mining", "petroleum"],
    "degas": ["degasification", "methane extraction", "mining", "safety"],
    "well": ["wellbore engineering", "well design", "petroleum engineering"],
    "completion": ["well completion", "petroleum engineering"],
    "wfl": ["wellhead facilities", "petroleum engineering"],
    
    # Cloud & DevOps
    # Related Domains: Distributed Systems, Software Engineering
    "cloud": ["cloud computing", "distributed systems", "infrastructure"],
    "aws": ["amazon web services", "cloud computing", "infrastructure"],
    "azure": ["microsoft azure", "cloud computing", "infrastructure"],
    "gcp": ["google cloud platform", "cloud computing", "infrastructure"],
    "k8s": ["kubernetes", "container orchestration", "devops"],
    "kubes": ["kubernetes", "container orchestration"],
    "docker": ["containerization", "containers", "devops"],
    "ci cd": ["continuous integration", "continuous deployment", "devops"],
    "devops": ["development operations", "deployment", "automation", "software engineering"],
    "microservices": ["microservices architecture", "distributed systems"],
    "serverless": ["serverless computing", "cloud functions"],
    "infra": ["infrastructure", "systems", "cloud"],
    
    # Security
    # Related Domains: Computer Science, Software Engineering, Cryptography
    "sec": ["security", "cybersecurity", "computer science"],
    "crypto": ["cryptography", "encryption", "security"],
    "infosec": ["information security", "cybersecurity", "computer science"],
    "cybersec": ["cybersecurity", "network security", "computer science"],
    "auth": ["authentication", "authorization", "security"],
    "pentest": ["penetration testing", "security testing", "cybersecurity"],
    
    # ========== MATHEMATICS ==========
    # Related Domains: Physics, Computer Science, Engineering, Statistics
    
    "math": ["mathematics", "computer science", "physics"],
    "maths": ["mathematics", "computer science", "physics"],
    "calc": ["calculus", "mathematics", "physics"],
    "multivar": ["multivariable calculus", "advanced calculus"],
    "ode": ["ordinary differential equations", "differential equations"],
    "pde": ["partial differential equations", "differential equations"],
    "la": ["linear algebra"],
    "lin alg": ["linear algebra"],
    "nt": ["number theory"],
    "prob": ["probability"],
    "prob stats": ["probability", "statistics"],
    "stats": ["statistics"],
    "stat": ["statistics"],
    "geom": ["geometry"],
    "topo": ["topology"],
    "ra": ["real analysis"],
    "ca math": ["complex analysis", "mathematical analysis"],
    "na": ["numerical analysis", "computational mathematics"],
    "fa": ["functional analysis", "mathematical analysis"],
    "la": ["linear algebra"],
    "dm": ["discrete mathematics"],
    "dmd": ["discrete mathematics"],
    "gt": ["graph theory", "group theory"],
    "ag": ["abstract algebra", "algebra"],
    "stoch": ["stochastic processes", "probability"],
    "opt": ["optimization", "mathematical optimization"],
    "lp": ["linear programming", "optimization"],
    "or": ["operations research", "optimization"],
    "game theory": ["game theory", "decision making", "economics"],
    
    # ========== PHYSICS ==========
    # Related Domains: Mathematics, Engineering, Chemistry, Astronomy
    
    "phys": ["physics", "mathematics", "engineering"],
    "mech": ["mechanics", "mechanical", "physics", "engineering"],
    "cm": ["classical mechanics", "mechanics", "physics", "mathematics"],
    "qm": ["quantum mechanics", "quantum physics"],
    "quantum": ["quantum mechanics", "quantum physics", "quantum computing"],
    "em": ["electromagnetism", "electrodynamics"],
    "thermo": ["thermodynamics", "heat transfer"],
    "stat mech": ["statistical mechanics", "thermodynamics"],
    "astro": ["astrophysics", "astronomy"],
    "cosmo": ["cosmology", "universe"],
    "particle": ["particle physics", "high energy physics"],
    "hep": ["high energy physics", "particle physics"],
    "condensed": ["condensed matter physics", "solid state physics"],
    "cmp": ["condensed matter physics", "solid state"],
    "nuclear": ["nuclear physics", "atomic physics"],
    "optics": ["optics", "light", "photonics"],
    "relativity": ["theory of relativity", "general relativity", "special relativity"],
    "gr": ["general relativity", "gravitation"],
    "sr": ["special relativity", "relativity"],
    "fluid": ["fluid dynamics", "fluid mechanics"],
    "cfd": ["computational fluid dynamics", "fluid mechanics"],
    "plasma": ["plasma physics", "fusion energy"],
    "acoustics": ["acoustics", "sound", "waves"],
    "waves": ["wave theory", "wave mechanics", "optics"],
    
    # ========== ENGINEERING ==========
    # Related Domains: Physics, Mathematics, Materials Science, Geology, Computer Science
    
    "engg": ["engineering", "physics", "mathematics"],
    "eng": ["engineering", "physics", "mathematics"],
    "mech eng": ["mechanical engineering", "mechanics", "physics", "mathematics"],
    "civil eng": ["civil engineering", "construction", "geology", "materials science"],
    "elec eng": ["electrical engineering", "electronics"],
    "ee": ["electrical engineering"],
    "ece": ["electronics and communication engineering"],
    "chem eng": ["chemical engineering", "process engineering"],
    "aero": ["aerospace engineering", "aeronautical engineering"],
    "auto": ["automotive engineering", "vehicle engineering"],
    "robotics": ["robotics", "automation", "control systems"],
    "control": ["control systems", "automation", "feedback systems"],
    "mechatronics": ["mechatronics", "mechanical electronics"],
    "biomed": ["biomedical engineering", "bioengineering"],
    "nano": ["nanotechnology", "nanoscience", "molecular manufacturing"],
    "materials": ["materials science", "materials engineering", "metallurgy"],
    "petro": ["petroleum engineering", "oil and gas"],
    "mining": ["mining engineering", "mineral extraction"],
    "geo": ["geology", "geophysics", "earth science"],
    "geotech": ["geotechnical engineering", "soil mechanics"],
    "structural": ["structural engineering", "structural design"],
    "thermal": ["thermal engineering", "heat transfer", "thermodynamics"],
    "hvac": ["heating ventilation air conditioning", "thermal systems"],
    "manufacturing": ["manufacturing engineering", "production engineering"],
    "industrial": ["industrial engineering", "operations research"],
    "ie": ["industrial engineering", "operations management"],
    "supply chain": ["supply chain management", "logistics", "operations"],
    "logistics": ["logistics", "supply chain", "operations"],
    
    # Petroleum & Mining Specific
    "reservoir": ["reservoir engineering", "petroleum engineering"],
    "drilling": ["drilling engineering", "petroleum engineering"],
    "production": ["production engineering", "petroleum engineering"],
    "subsea": ["subsea engineering", "offshore engineering"],
    "offshore": ["offshore engineering", "marine engineering"],
    "cbm": ["coal bed methane", "methane extraction"],
    "degas": ["degasification", "methane extraction"],
    "ventilation": ["mine ventilation", "safety engineering"],
    "ground control": ["ground control", "rock mechanics", "mining safety"],
    "rock mech": ["rock mechanics", "geomechanics"],
    
    # ========== BIOLOGY & LIFE SCIENCES ==========
    # Related Domains: Chemistry, Medicine, Environmental Science, Computer Science
    
    "bio": ["biology", "biological sciences", "chemistry", "medicine"],
    "genetics": ["genetics", "heredity", "dna", "biology", "medicine"],
    "genomics": ["genomics", "genetic sequencing", "bioinformatics", "computer science", "biology"],
    "bioinfo": ["bioinformatics", "computational biology"],
    "mol bio": ["molecular biology", "biochemistry"],
    "biochem": ["biochemistry", "metabolic processes"],
    "microbio": ["microbiology", "microorganisms"],
    "ecology": ["ecology", "ecosystems", "environmental science"],
    "evo": ["evolution", "evolutionary biology"],
    "anatomy": ["anatomy", "human anatomy", "physiology"],
    "physio": ["physiology", "human physiology"],
    "zoology": ["zoology", "animal science"],
    "botany": ["botany", "plant science"],
    "marine bio": ["marine biology", "oceanography", "aquatic biology"],
    "neuro": ["neuroscience", "neurobiology", "brain"],
    "cell bio": ["cell biology", "cytology", "cells"],
    "immunology": ["immunology", "immune system"],
    "pathology": ["pathology", "disease mechanisms"],
    "pharma": ["pharmacology", "pharmaceuticals", "drugs"],
    "toxicology": ["toxicology", "poisons", "environmental health"],
    "biotech": ["biotechnology", "genetic engineering"],
    
    # ========== MEDICINE & HEALTH ==========
    # Related Domains: Biology, Chemistry, Psychology, Pharmacology
    
    "med": ["medicine", "medical", "biology", "chemistry"],
    "clinical": ["clinical medicine", "patient care", "medicine"],
    "surgery": ["surgery", "surgical techniques", "medicine", "anatomy"],
    "radiology": ["radiology", "medical imaging", "diagnostic imaging"],
    "path": ["pathology", "disease diagnosis"],
    "derm": ["dermatology", "skin"],
    "cardio": ["cardiology", "heart"],
    "neuro med": ["neurology", "nervous system"],
    "ortho": ["orthopedics", "musculoskeletal"],
    "peds": ["pediatrics", "child health"],
    "obgyn": ["obstetrics gynecology", "women health"],
    "psych": ["psychiatry", "mental health", "psychology"],
    "epi": ["epidemiology", "public health"],
    "public health": ["public health", "epidemiology", "population health"],
    "nursing": ["nursing", "patient care"],
    "dentistry": ["dentistry", "dental"],
    "vet": ["veterinary medicine", "animal health"],
    "sports med": ["sports medicine", "athletic training"],
    "rehab": ["rehabilitation", "physical therapy"],
    "nutrition": ["nutrition", "dietetics", "diet"],
    "wellness": ["wellness", "health promotion"],
    "fitness": ["fitness", "exercise", "physical training"],
    
    # ========== CHEMISTRY ==========
    # Related Domains: Physics, Biology, Materials Science, Environmental Science
    
    "chem": ["chemistry", "physics", "biology"],
    "org chem": ["organic chemistry", "carbon compounds", "chemistry", "biology"],
    "inorg": ["inorganic chemistry", "inorganic", "chemistry", "materials science"],
    "phys chem": ["physical chemistry", "chemical physics"],
    "analytical": ["analytical chemistry", "chemical analysis"],
    "biochem": ["biochemistry", "biological chemistry"],
    "polymer": ["polymer chemistry", "macromolecules"],
    "materials chem": ["materials chemistry", "solid state chemistry"],
    "env chem": ["environmental chemistry", "green chemistry"],
    "petrochem": ["petrochemistry", "petroleum chemistry"],
    
    # ========== EARTH & ENVIRONMENTAL SCIENCES ==========
    # Related Domains: Physics, Chemistry, Engineering, Biology
    
    "geo": ["geology", "earth science", "physics", "chemistry"],
    "geology": ["geology", "earth science", "physics"],
    "geophys": ["geophysics", "earth physics", "physics", "mathematics"],
    "meteo": ["meteorology", "atmospheric science"],
    "climate": ["climate science", "climatology", "global warming"],
    "ocean": ["oceanography", "marine science"],
    "env sci": ["environmental science", "environmental studies"],
    "env eng": ["environmental engineering", "sustainability"],
    "sustainability": ["sustainability", "sustainable development", "green"],
    "ecology": ["ecology", "ecosystems"],
    "conservation": ["conservation biology", "wildlife conservation"],
    "paleo": ["paleontology", "fossils", "ancient life"],
    "hydrology": ["hydrology", "water resources"],
    "soil": ["soil science", "pedology", "agriculture"],
    
    # ========== SOCIAL SCIENCES ==========
    # Related Domains: Humanities, Education, Business, Economics
    
    "psych": ["psychology", "psychological", "neuroscience", "medicine"],
    "soc": ["sociology", "social science", "anthropology", "humanities"],
    "anthro": ["anthropology", "cultural studies", "history", "sociology"],
    "econ": ["economics", "economy"],
    "pol sci": ["political science", "politics", "government"],
    "ir": ["international relations", "diplomacy", "foreign policy"],
    "geo pol": ["geopolitics", "international relations"],
    "public pol": ["public policy", "policy analysis"],
    "urban": ["urban studies", "city planning", "urban sociology"],
    "demography": ["demography", "population studies"],
    "crim": ["criminology", "criminal justice"],
    "soc work": ["social work", "welfare"],
    "gender": ["gender studies", "women studies", "feminism"],
    "ethnic": ["ethnic studies", "race studies"],
    "ling": ["linguistics", "language science"],
    "socio ling": ["sociolinguistics", "language and society"],
    "psycholing": ["psycholinguistics", "language and mind"],
    
    # ========== BUSINESS & MANAGEMENT ==========
    # Related Domains: Economics, Mathematics, Computer Science, Psychology
    
    "biz": ["business", "commerce", "economics"],
    "mgmt": ["management", "administration", "business", "psychology"],
    "fin": ["finance", "financial", "economics", "mathematics"],
    "acct": ["accounting", "accountancy"],
    "marketing": ["marketing", "market research"],
    "hr": ["human resources", "personnel management", "talent management"],
    "hcm": ["human capital management", "human resources"],
    "ob": ["organizational behavior", "management"],
    "strategy": ["strategic management", "business strategy"],
    "ops": ["operations management", "operations research"],
    "scm": ["supply chain management", "logistics"],
    "entrepreneur": ["entrepreneurship", "startup", "venture"],
    "innovation": ["innovation management", "technology management"],
    "leadership": ["leadership", "management"],
    "project mgmt": ["project management", "program management"],
    "pm": ["project management", "product management"],
    "product": ["product management", "product development"],
    "consulting": ["management consulting", "strategy consulting"],
    "ib": ["international business", "global business"],
    "corporate": ["corporate strategy", "corporate finance"],
    "investment": ["investment", "portfolio management"],
    "banking": ["banking", "financial services"],
    "fintech": ["financial technology", "digital finance"],
    "risk": ["risk management", "financial risk"],
    "derivatives": ["financial derivatives", "risk management"],
    "accounting": ["accounting", "financial accounting", "audit"],
    
    # ========== HUMANITIES ==========
    # Related Domains: Social Sciences, Education, Psychology
    
    "phil": ["philosophy", "humanities"],
    "ethics": ["ethics", "moral philosophy", "philosophy", "social sciences"],
    "meta": ["metaphysics", "ontology", "philosophy"],
    "epist": ["epistemology", "theory of knowledge"],
    "logic": ["logic", "philosophical logic"],
    "aesthetics": ["aesthetics", "philosophy of art"],
    "hist": ["history", "historical"],
    "archaeo": ["archaeology", "ancient history"],
    "art hist": ["art history", "history of art"],
    "lit": ["literature", "literary studies"],
    "comp lit": ["comparative literature", "world literature"],
    "poetry": ["poetry", "poetics", "verse"],
    "drama": ["drama", "theater", "theatre"],
    "film": ["film studies", "cinema", "movies"],
    "music": ["music", "musicology", "music theory"],
    "classics": ["classical studies", "ancient greek", "latin"],
    "religion": ["religious studies", "theology", "divinity"],
    "theology": ["theology", "religious studies"],
    "myth": ["mythology", "folklore"],
    "lang": ["language", "linguistics"],
    "translation": ["translation studies", "interpretation"],
    
    # ========== LAW ==========
    # Related Domains: Business, Political Science, Economics, Humanities
    
    "law": ["law", "legal studies", "business", "political science"],
    "juris": ["jurisprudence", "legal philosophy", "philosophy", "law"],
    "const": ["constitutional law", "constitution", "political science", "law"],
    "crim law": ["criminal law", "criminal justice"],
    "civil law": ["civil law", "private law"],
    "corp law": ["corporate law", "business law"],
    "ip": ["intellectual property", "patents", "copyrights"],
    "tort": ["tort law", "civil wrongs"],
    "contract": ["contract law", "agreements"],
    "env law": ["environmental law", "regulatory law"],
    "labor law": ["labor law", "employment law"],
    "intl law": ["international law", "global law"],
    "human rights": ["human rights law", "civil rights"],
    "evidence": ["evidence law", "legal proof"],
    "tax law": ["tax law", "taxation"],
    
    # ========== EDUCATION ==========
    # Related Domains: Psychology, Sociology, Computer Science, Humanities
    
    "ed": ["education", "educational studies", "psychology", "sociology"],
    "pedagogy": ["pedagogy", "teaching methods", "education", "psychology"],
    "curriculum": ["curriculum development", "instructional design", "education"],
    "higher ed": ["higher education", "university", "college"],
    "k12": ["k12 education", "primary education", "secondary education"],
    "early child": ["early childhood education", "preschool"],
    "special ed": ["special education", "inclusive education"],
    "stem": ["stem education", "science technology engineering math"],
    "ed tech": ["educational technology", "e-learning", "online learning"],
    "distance": ["distance learning", "online education", "remote learning"],
    "assessment": ["educational assessment", "testing", "evaluation"],
    "ed psych": ["educational psychology", "learning psychology"],
    
    # ========== ARTS & DESIGN ==========
    # Related Domains: Engineering, Computer Science, Humanities, Communication
    
    "art": ["art", "fine arts", "visual arts", "humanities"],
    "design": ["design", "graphic design", "visual communication", "computer science"],
    "arch": ["architecture", "architectural design", "engineering", "mathematics"],
    "int design": ["interior design", "spatial design"],
    "ind design": ["industrial design", "product design"],
    "ux ui": ["user experience", "user interface", "design"],
    "typography": ["typography", "letterform design", "fonts"],
    "color": ["color theory", "palette design"],
    "photo": ["photography", "photographic arts"],
    "animation": ["animation", "motion graphics"],
    "game design": ["game design", "video game development"],
    "fashion": ["fashion design", "apparel design"],
    "theater": ["theater", "theatre", "dramatic arts"],
    "perf arts": ["performing arts", "dance", "music performance"],
    "creative": ["creative arts", "creative practice"],
    "visual": ["visual arts", "visual communication"],
    
    # ========== COMMUNICATION & MEDIA ==========
    # Related Domains: Humanities, Social Sciences, Business, Education
    
    "comm": ["communication", "communications", "humanities", "social sciences"],
    "media": ["media studies", "mass media", "communication", "social sciences"],
    "journalism": ["journalism", "news", "reporting", "communication"],
    "pr": ["public relations", "communications"],
    "advertising": ["advertising", "marketing communications"],
    "broadcast": ["broadcasting", "television", "radio"],
    "digital media": ["digital media", "new media"],
    "social media": ["social media", "digital marketing"],
    
    # ========== MISCELLANEOUS ==========
    
    "research": ["research methods", "methodology"],
    "stats methods": ["statistical methods", "data analysis"],
    "survey": ["survey research", "questionnaire design"],
    "qual": ["qualitative research", "qualitative methods"],
    "quant": ["quantitative research", "quantitative methods"],
    "mixed methods": ["mixed methods research", "triangulation"],
    "academic": ["academic writing", "scholarly communication"],
    "technical": ["technical writing", "documentation"],
    "sci comm": ["science communication", "public understanding of science"],
    
    # Generic terms
    "textbook": ["textbook", "course book", "academic book"],
    "reference": ["reference", "handbook", "encyclopedia"],
    "guide": ["guide", "manual", "handbook"],
    "intro": ["introduction", "introductory", "basics", "fundamentals"],
    "advanced": ["advanced", "graduate level", "specialized"],
    "theory": ["theory", "theoretical", "foundations"],
    "practical": ["practical", "applied", "hands-on"],
    "case studies": ["case studies", "examples", "applications"],
}